name: Gitleaks

on: [push,pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: customized gitleaks
      uses: sushi2k/gitleaks-action@master
      with:
         extra-args: -o gitleaks.sarif -f sarif
    - name: List files in the workspace
      if: always()
      run: |
        ls ${{ github.workspace }}
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: gitleaks
        path: gitleaks.sarif
    - name: Upload gitleaks report
      if: always()
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: gitleaks.sarif
      # with:
      #   extra-args: -f sarif -r gitleaks.sarif
    # - name: Upload Test results
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: Gitleaks report
    #     path: ${{github.workspace}}/gitleaks.sarif
